apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vernemq-reader
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods","services","endpoints"]
    verbs: ["get","list","watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vernemq-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: vernemq-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vernemq-reader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vernemq-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vernemq
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vernemq
  template:
    metadata:
      labels:
        app: vernemq
    spec:
      serviceAccountName: vernemq-sa
      nodeSelector:
        worker: "1"
      containers:
        - name: vernemq
          image: docker.io/library/vernemq-with-exporter
          imagePullPolicy: IfNotPresent
          env:
            - name: DOCKER_VERNEMQ_ACCEPT_EULA
              value: "yes"
            - name: DOCKER_VERNEMQ_DISCOVERY_KUBERNETES
              value: "off"
            - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
              value: "on"
          ports:
            - name: mqtt
              containerPort: 1883
            - name: metrics
              containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: vernemq
  namespace: default
spec:
  selector:
    app: vernemq
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: metrics
      port: 9100
      targetPort: 9100