networks:
  benchnet:
    driver: bridge

services:
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    image: mosquitto-with-exporter
    container_name: mosquitto
    hostname: mosquitto
    domainname: benchnet
    networks:
      benchnet:
        aliases: ["mosquitto", "mqtt", "broker"]
    ports: ["1883:1883"]
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    healthcheck:
      test: ["CMD-SHELL","nc -z 127.0.0.1 1883"]
      interval: 15s
      timeout: 1s
      retries: 20
      start_period: 2s

  runner01:
    image: ps_bench-runner:latest
    hostname: runner01
    domainname: benchnet
    networks: [benchnet]
    environment:
      SELECTED_SCENARIO: mqtt_single_node_stress
      BROKER_HOST: mqtt
      BROKER_PORT: 1883
      NODE_BASE: runner1
      ADD_NODE_TO_SUFFIX: "false"
      RELEASE_COOKIE: ps_bench_cookie
      SCEN_DIR: /app/configs/initial_tests/scenarios
    volumes:
      - ./out/runner01:/app/out
      - ./results:/app/results 
      - ./configs:/app/configs:ro 
    depends_on:
      mosquitto:
        condition: service_healthy