networks:
  benchnet:
    driver: bridge

services:
  vernemq:
    build:
      context: .
      dockerfile: Dockerfile.vernemq
    image: vernemq-with-exporter
    container_name: vernemq
    hostname: vernemq
    domainname: benchnet
    networks:
      benchnet:
        aliases: ["vernemq", "mqtt", "broker"]
    ports: ["1883:1883"]
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
    healthcheck:
      test: ["CMD-SHELL","vernemq ping"]
      interval: 15s
      timeout: 1s
      retries: 20
      start_period: 2s

  runner01:
    image: ps_bench-runner:latest
    hostname: runner01
    domainname: benchnet
    networks: [benchnet]
    environment:
      SELECTED_SCENARIO: mqtt_single_node_stress
      BROKER_HOST: mqtt
      BROKER_PORT: 1883
      NODE_BASE: runner1
      ADD_NODE_TO_SUFFIX: "false"
      RELEASE_COOKIE: ps_bench_cookie
      SCEN_DIR: /app/configs/initial_tests/scenarios
      DEVICE_DIR: /app/configs/initial_tests/devices
      DEPLOY_DIR: /app/configs/initial_tests/deployments
    volumes:
      - ./out/runner01:/app/out
      - ./results:/app/results 
      - ./configs:/app/configs:ro 
    depends_on:
      vernemq:
        condition: service_healthy
