networks:
  benchnet:
    driver: bridge

services:
  runnerDDS1:
    image: ps_bench-runner:latest
    container_name: runnerDDS1
    hostname: runnerDDS1
    domainname: benchnet
    networks:
      benchnet:
        aliases:
          - runnerDDS1.benchnet
    environment:
      DIST_MODE: name
      NODE_BASE: runner1
      NODE_HOST_OVERRIDE: ${NODE1_HOST_OVERRIDE:-}
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-dds_test}
      SCEN_DIR: /app/configs/builtin-test-suites/testcases/qos-variation/1-node/smart_home_dds_high
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: qossuite_smart_home_dds_high_1_node
    volumes:
      - ./out/runnerDDS1:/app/out
      - ./results:/app/results
