networks:
  benchnet:
    driver: bridge

services:
  nanomq:
    build:
      context: .
      dockerfile: Dockerfile.nanomq
    image: nanomq-with-exporter
    container_name: nanomq
    hostname: nanomq
    domainname: benchnet
    networks:
      benchnet:
        aliases: ["nanomq", "mqtt", "broker"]
    ports: ["1883:1883"]
    healthcheck:
      test: ["CMD-SHELL","nc -z 127.0.0.1 1883"]
      interval: 15s
      timeout: 1s
      retries: 20
      start_period: 2s

  runnerMQTT1:
    image: ps_bench-runner:latest
    container_name: runnerMQTT1
    hostname: runnerMQTT1
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerMQTT1.benchnet
    environment:
      DIST_MODE: name 
      NODE_BASE: runner1
      NODE_HOST_OVERRIDE: ${NODE1_HOST_OVERRIDE:-}
      BROKER_HOST: nanomq
      BROKER_PORT: 1883
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-mqtt_test}
      SCEN_DIR: ${SCEN_DIR:-/app/configs/builtin-test-suites/testcases/scalability/1-node/smart_home_mqttv5/1x}
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: ${SCENARIO:-scalabilitysuite_smart_home_mqttv5_1_node}
    volumes:
      - ./out/runnerMQTT1:/app/out
      - ./results:/app/results
    depends_on:
      nanomq:
        condition: service_healthy
