networks:
  benchnet:
    driver: bridge

services:
  runnerDDS1:
    image: ps_bench-runner:latest
    container_name: runnerDDS1
    hostname: runnerDDS1
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerDDS1.benchnet
    environment:
      DIST_MODE: name
      SELECTED_SCENARIO: ${SCENARIO:-dds_multi_node_moderate}
      NODE_BASE: runner1
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-dds_test}
      SCEN_DIR: /app/configs/initial_tests/scenarios
    volumes:
      - ./out/runnerDDS1:/app/out
      - ./results:/app/results

  runnerDDS2:
    image: ps_bench-runner:latest
    container_name: runnerDDS2
    hostname: runnerDDS2
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerDDS2.benchnet
    environment:
      DIST_MODE: name     
      SELECTED_SCENARIO: ${SCENARIO:-dds_multi_node_moderate}
      NODE_BASE: runner2
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-dds_test}
      SCEN_DIR: /app/configs/initial_tests/scenarios
    volumes:
      - ./out/runnerDDS2:/app/out
      - ./results:/app/results

  runnerDDS3:
    image: ps_bench-runner:latest
    container_name: runnerDDS3
    hostname: runnerDDS3
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerDDS3.benchnet
    environment:
      DIST_MODE: name
      SELECTED_SCENARIO: ${SCENARIO:-dds_multi_node_moderate}
      NODE_BASE: runner3
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-dds_test}
      SCEN_DIR: /app/configs/initial_tests/scenarios
    volumes:
      - ./out/runnerDDS3:/app/out
      - ./results:/app/results

  runnerDDS4:
    image: ps_bench-runner:latest
    container_name: runnerDDS4
    hostname: runnerDDS4
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerDDS4.benchnet
    environment:
      DIST_MODE: name
      SELECTED_SCENARIO: ${SCENARIO:-dds_multi_node_moderate}
      NODE_BASE: runner4
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-dds_test}
      SCEN_DIR: /app/configs/initial_tests/scenarios
    volumes:
      - ./out/runnerDDS4:/app/out
      - ./results:/app/results

  runnerDDS5:
    image: ps_bench-runner:latest
    container_name: runnerDDS5
    hostname: runnerDDS5
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerDDS5.benchnet
    environment:
      DIST_MODE: name
      SELECTED_SCENARIO: ${SCENARIO:-dds_multi_node_moderate}
      NODE_BASE: runner5
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-dds_test}
      SCEN_DIR: /app/configs/initial_tests/scenarios
    volumes:
      - ./out/runnerDDS5:/app/out
      - ./results:/app/results