networks:
  benchnet:
    driver: bridge

services:
  emqx:
    build:
      context: .
      dockerfile: Dockerfile.emqx
    image: emqx-with-exporter
    container_name: emqx
    hostname: emqx
    domainname: benchnet
    networks:
      benchnet:
        aliases: ["emqx", "mqtt", "broker"]
    ports: ["1883:1883"]
    environment:
      EMQX_LOG__LEVEL: debug            
      EMQX_MQTT__KEEPALIVE: 120s        
      EMQX_MQTT__IDLE_TIMEOUT: 60s
      EMQX_MQTT__MAX_PACKET_SIZE: 10MB  
      EMQX_ALLOW_ANONYMOUS: "true" 
    healthcheck:
      test: ["CMD-SHELL","emqx ping"]
      interval: 15s
      timeout: 1s
      retries: 20
      start_period: 2s

  runnerMQTT1:
    image: ps_bench-runner:latest
    container_name: runnerMQTT1
    hostname: runnerMQTT1
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerMQTT1.benchnet
    environment:
      DIST_MODE: name 
      NODE_BASE: runner1
      NODE_HOST_OVERRIDE: ${NODE1_HOST_OVERRIDE:-}
      BROKER_HOST: emqx
      BROKER_PORT: 1883
      ADD_NODE_TO_SUFFIX: "true"
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-mqtt_test}
      SCEN_DIR: /app/configs/builtin-test-suites/testcases/qos-variation/1-node/smart_home_mqttv5_high
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: qossuite_smart_home_mqttv5_high_1_node
    volumes:
      - ./out/runnerMQTT1:/app/out
      - ./results:/app/results
    depends_on:
      emqx:
        condition: service_healthy
