networks:
  benchnet:
    driver: bridge

services:
  vernemq:
    build:
      context: .
      dockerfile: Dockerfile.vernemq
    image: vernemq-with-exporter
    container_name: vernemq
    hostname: vernemq
    domainname: benchnet
    networks:
      benchnet:
        aliases: ["vernemq", "mqtt", "broker"]
    ports: ["1883:1883"]
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
      DOCKER_VERNEMQ_LISTENER__TCP__DEFAULT: "0.0.0.0:1883"
      DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS: "3,4,5"
    healthcheck:
      test: ["CMD-SHELL", "ss -ltn | grep -q ':1883'"]
      interval: 15s
      timeout: 1s
      retries: 20
      start_period: 2s

  runnerMQTT1:
    image: ps_bench-runner:latest
    container_name: runnerMQTT1
    hostname: runnerMQTT1
    domainname: benchnet
    networks: 
      benchnet:
        aliases:
          - runnerMQTT1.benchnet
    environment:
      DIST_MODE: name 
      NODE_BASE: runner1
      NODE_HOST_OVERRIDE: ${NODE1_HOST_OVERRIDE:-}
      BROKER_HOST: vernemq
      BROKER_PORT: 1883
      ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-false}
      RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}
      RUN_TAG: ${RUN_TAG:-mqtt_test}
      SCEN_DIR: /app/configs/builtin-test-suites/testcases/qos-variation/1-node/smart_home_mqttv5_high
      DEVICE_DIR: /app/configs/builtin-test-suites/devices
      DEPLOY_DIR: /app/configs/builtin-test-suites/deployments
      SCENARIO: qossuite_smart_home_mqttv5_high_1_node
    volumes:
      - ./out/runnerMQTT1:/app/out
      - ./results:/app/results
    depends_on:
      vernemq:
        condition: service_healthy
