networks:
  benchnet: {}

x-runner-env: &runner-env
  SELECTED_SCENARIO: ${SCENARIO}
  BROKER_HOST: mqtt
  BROKER_PORT: ${MOSQUITTO_PORT:-1883}
  RUN_TAG: ${RUN_TAG:-run1}
  ADD_NODE_TO_SUFFIX: ${ADD_NODE_TO_SUFFIX:-true}
  RELEASE_COOKIE: ${RELEASE_COOKIE:-ps_bench_cookie}

services:
  mosquitto:
    image: eclipse-mosquitto:2
    profiles: ["mosq"]
    networks:
      benchnet:
        aliases: ["mosquitto", "mqtt", "broker", "mqtt-broker"]
    ports: ["${MOSQUITTO_PORT:-1883}:1883"]
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 1883"]
      interval: 2s
      timeout: 1s
      retries: 20

  emqx:
    image: emqx/emqx:latest
    profiles: ["emqx"]
    networks:
      benchnet:
        aliases: ["emqx", "mqtt", "broker", "mqtt-broker"]
    ports: ["${EMQX_PORT:-2883}:1883"]
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 1883"]
      interval: 2s
      timeout: 1s
      retries: 20

  runner01:
    image: ps_bench-runner:latest
    profiles: ["bench"]
    networks: [benchnet]
    environment: *runner-env
    volumes:
      - ./out/runner01:/app/out

  runner02:
    image: ps_bench-runner:latest
    profiles: ["bench"]
    networks: [benchnet]
    environment: *runner-env
    volumes:
      - ./out/runner02:/app/out

  runner03:
    image: ps_bench-runner:latest
    profiles: ["bench"]
    networks: [benchnet]
    environment: *runner-env
    volumes:
      - ./out/runner03:/app/out

  runner04:
    image: ps_bench-runner:latest
    profiles: ["bench"]
    networks: [benchnet]
    environment: *runner-env
    volumes:
      - ./out/runner04:/app/out

  runner05:
    image: ps_bench-runner:latest
    profiles: ["bench"]
    networks: [benchnet]
    environment: *runner-env
    volumes:
      - ./out/runner05:/app/out
