apiVersion: apps/v1
kind: Deployment
metadata:
  name: mochi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mochi
  template:
    metadata:
      labels:
        app: mochi
    spec:
      nodeSelector:
        worker: "1"
      containers:
        - name: mochi
          image: docker.io/library/mochi-with-exporter
          imagePullPolicy: Never
          ports:
            - name: mqtt
              containerPort: 1883
            - name: metrics
              containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: mochi
spec:
  selector:
    app: mochi
  ports:
    - name: mochi
      port: 1883
      targetPort: 1883
    - name: metrics
      port: 9100
      targetPort: 9100